#!/usr/bin/env bash
# byom.sh - Bring Your Own Model. Put a different mouth under the same fly.
#
#   ./byom.sh <base-model> [name]
#
#   ./byom.sh llama3.1:8b                 ->  glados-llama3.1
#   ./byom.sh qwen3:32b big               ->  glados-big
#   ./byom.sh hf.co/user/repo:Q4_K_M      ->  glados-repo
#
# WHY THIS EXISTS
#
# The fly is the part of her that is ours. `qwen2.5:7b-instruct` is a borrowed
# language organ, chosen because it fits in the RAM of one 2013 Xeon - not
# because it is the best mouth she could have. When you have a bigger box, or
# next year's 30B, you should be able to swap the mouth without touching the
# animal. That is the whole architecture: the fly holds the state, the language
# model is a stateless renderer of it, and renderers are replaceable.
#
# So: same persona, same sampling band, same five axes, same 164,587 neurons.
# Different weights doing the talking.
#
# THE ONE RULE: THE NAME IS THE FENCE
#
# gladosd decides what the fly drives by PREFIX (mood.model_coupled): any tag
# whose name starts with an entry in `mood_models` - which is `["glados"]` -
# gets the state clause and the temperature nudge. Any tag that does not goes
# through byte-identical.
#
# That is deliberate, and it is why this script is 80 lines rather than a
# server change: `glados-llama3.1`, `glados-big` and `glados-whatever-you-like`
# are coupled the moment they exist, with no config edit, no restart, and no
# risk to the tag your other software already calls. Name it `mistral-glados`
# and the fly will ignore it forever, which is why this script insists.
set -euo pipefail

BASE="${1:-}"
NAME="${2:-}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${GLADOS_PREFIX:-glados}"

if [[ -z "$BASE" ]]; then
  sed -n '2,9p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
  echo "Any Ollama model reference works as a base: a local tag, a registry"
  echo "model, or hf.co/<user>/<repo>:<quant>."
  exit 2
fi

# Derive a name from the base when none was given: drop any registry path and
# any :tag, so `hf.co/user/qwen3-coder:Q4_K_M` becomes `glados-qwen3-coder`.
if [[ -z "$NAME" ]]; then
  NAME="${BASE##*/}"
  NAME="${NAME%%:*}"
fi
# Enforce the fence rather than warn about it. A silently-uncoupled GLaDOS is
# the single most disappointing possible outcome of running this script.
[[ "$NAME" == "$PREFIX"* ]] || NAME="${PREFIX}-${NAME}"

MODELFILE="$HERE/Modelfile.$NAME"

# Who she is, lifted out of `Modelfile` rather than retyped here, so there is
# exactly one copy of the persona in the repository and a BYO build can never
# drift into being a slightly different character. This assumes the SYSTEM
# block is one line, which it is - and if someone reflows it, this fails loudly
# instead of generating a GLaDOS with no personality at all.
PERSONA="$(sed -n 's/^SYSTEM """\(.*\)"""$/\1/p' "$HERE/Modelfile")"
[[ -n "$PERSONA" ]] || {
  echo "could not read the SYSTEM line out of $HERE/Modelfile." >&2
  echo "It should be one line: SYSTEM \"\"\"...\"\"\"" >&2
  exit 1
}

command -v ollama >/dev/null 2>&1 || {
  echo "ollama not found. Install it from https://ollama.com and try again." >&2
  exit 1
}
ollama list >/dev/null 2>&1 || {
  echo "ollama is installed but not answering. Start it with 'ollama serve'." >&2
  exit 1
}

if ollama list | awk 'NR>1{print $1}' | grep -qx "$BASE"; then
  echo "base $BASE: already local (the new tag will cost no extra disk)"
else
  echo "base $BASE: not local, pulling it"
  ollama pull "$BASE"
fi

# The persona and the sampling band are copied from `Modelfile`, which is the
# single source of truth for who she is. Only `FROM` changes.
#
# Two PARAMETER lines are load-bearing and are the easiest thing to drop when
# people hand-roll this file:
#
#   temperature  - the fly may only RAISE a temperature the caller already set,
#                  by at most 0.3, never past 0.9. A body with no temperature
#                  at all gets no nudge, because inventing sampling for a
#                  caller that chose the backend default is not our business.
#                  So this line is what gives arousal somewhere to push.
#   num_predict  - she is a one-liner. Without it a 32B will write you an essay
#                  in character, which is worse than it sounds.
#
# No num_gpu / num_thread here, on purpose. The deployed values are right for
# one specific 2013 Xeon and actively wrong for your box; see
# Modelfile.cpu-tuned for what they are and what they are worth.
cat > "$MODELFILE" <<EOF
# GLaDOS, with $BASE as the language organ. Generated by byom.sh.
#
#   ollama create $NAME -f $(basename "$MODELFILE")
#
# Coupled to the fly because the name starts with '$PREFIX'. Nothing else is
# needed - no config edit, no restart. See docs/BYOM.md.
FROM $BASE

SYSTEM """$PERSONA"""

PARAMETER temperature 0.7
PARAMETER num_predict 100
EOF

echo "wrote $(basename "$MODELFILE")"
ollama create "$NAME" -f "$MODELFILE"

# Tell the user whether the fly will actually reach this tag, from the server's
# own mouth rather than from this script's assumptions. If gladosd is not
# running here, say so instead of guessing.
HEALTH="${GLADOS_HEALTH:-127.0.0.1:11434}"
echo
if PREFIXES=$(curl -fsS --max-time 3 "http://$HEALTH/health" 2>/dev/null \
              | python3 -c 'import json,sys; print(" ".join(json.load(sys.stdin)["mood"]["coupled_models"]))' 2>/dev/null); then
  COUPLED=no
  for p in $PREFIXES; do [[ "$NAME" == "$p"* ]] && COUPLED=yes; done
  if [[ "$COUPLED" == yes ]]; then
    echo "gladosd on $HEALTH couples [$PREFIXES] - '$NAME' matches. The fly drives it."
  else
    echo "gladosd on $HEALTH couples [$PREFIXES] - '$NAME' does NOT match, so it"
    echo "will answer with the persona but no moods. Add it to config.json:"
    echo "  \"mood_models\": [$(for p in $PREFIXES; do printf '"%s", ' "$p"; done)\"$NAME\"]"
  fi
else
  echo "No gladosd answering on $HEALTH, so this is the persona layer only:"
  echo "'$NAME' is a working GLaDOS with a fixed mood. The moods arrive when"
  echo "the fly and the server are up - see docs/BYOM.md and docs/REPRODUCE.md."
fi

echo
echo "Try her:   ollama run $NAME"
echo "Remove:    ollama rm $NAME          (cannot harm the base model)"
